
index:
  path: /
  controller: App\Controller\DefaultController::index
search_items:
  path: items/search
  controller: App\Controller\ItemsController::search
  methods: GET

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
generate_pdf:
    path: /reservations/pdf
    controller: App\Controller\ReservationbackController::generatePdf
app_generate_qr_code:
    path: '/generate/qr-code'
    controller: App\Controller\EventController::generateQrCode
    methods: ['GET'] # Ajoutez cette ligne si n√©cessaire
search_by_place:
    path: searchByPlace
    controller: App\Controller\EventController::searchByPlace

app_annoncesback_show:
    path: '/annoncesback/{id}'
    controller: 'App\Controller\AnnoncesbackController::show'
